FROM osrf/ros:humble-desktop-full

WORKDIR /ws
ARG USER=weng
ARG UID=1000
ARG GID=1000

RUN groupadd -g ${GID} ${USER} \
 && useradd -m -u ${UID} -g ${GID} -s /bin/bash ${USER} \ 
 && echo "${USER} ALL=(ALL) NOPASSWD: ALL" > "/etc/sudoers.d/${USER}"

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3-colcon-common-extensions \
    python3-pip \
    git \
    terminator \
    ros-humble-moveit* \
    ros-humble-ros2-controllers \
    ros-humble-ros2-control \
    ros-humble-dynamixel-sdk \
    && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
USER ${USER}

ENTRYPOINT ["/entrypoint.sh" , "terminator"]
